//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupSports.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATHLETE
    {
        public int AthleteId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Discipline { get; set; }
        public Nullable<int> AgeCategory { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
