//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupSports.DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GSEntities : DbContext
    {
        public GSEntities()
            : base("name=GSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ATHLETE> ATHLETE { get; set; }
        public virtual DbSet<COACH> COACH { get; set; }
        public virtual DbSet<MACROCICLO> MACROCICLO { get; set; }
        public virtual DbSet<MESOCICLO> MESOCICLO { get; set; }
        public virtual DbSet<SESION> SESION { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<WORKPLAN> WORKPLAN { get; set; }
        public virtual DbSet<WORKWEEK> WORKWEEK { get; set; }
    }
}
