//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupSports.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESION
    {
        public int SesionId { get; set; }
        public Nullable<int> WorkWeekId { get; set; }
        public string Nombre { get; set; }
        public string Objective { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<bool> Asistencia { get; set; }
        public Nullable<bool> Cumplimiento { get; set; }
        public Nullable<System.TimeSpan> HoraAsistencia { get; set; }
        public Nullable<System.TimeSpan> HoraCumplimiento { get; set; }
        public string Bitacora { get; set; }
        public bool Estado { get; set; }
    
        public virtual WORKWEEK WORKWEEK { get; set; }
    }
}
