//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupSports.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.ATHLETE = new HashSet<ATHLETE>();
            this.COACH = new HashSet<COACH>();
        }
    
        public int UserId { get; set; }
        public string UserLogin { get; set; }
        public string UserPass { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string CellPhone { get; set; }
        public string Adress { get; set; }
        public string EmailAdress { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public Nullable<int> UserType { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATHLETE> ATHLETE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COACH> COACH { get; set; }
    }
}
