//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupSports.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKPLAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WORKPLAN()
        {
            this.MACROCICLO = new HashSet<MACROCICLO>();
        }
    
        public int WorkPlanId { get; set; }
        public string Name { get; set; }
        public string Objective { get; set; }
        public Nullable<int> CoachId { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public bool Estado { get; set; }
    
        public virtual COACH COACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MACROCICLO> MACROCICLO { get; set; }
    }
}
